//This script was generated by the Haxe compiler and might be out of date.
//Its original source code written in Haxe is available here :
//https://github.com/orwenn22/randompatterns/blob/main/src/Main.hx

(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	var _g = [];
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	_g.push(0);
	var pattern = _g;
	var drawingcanvas = window.document.getElementById("drawingcanvas");
	var context = drawingcanvas.getContext("2d",null);
	context.fillStyle = "#000000";
	context.fillRect(0,0,512,512);
	context.stroke();
	var generatebutton = window.document.getElementById("generatebutton");
	generatebutton.onclick = function() {
		context.fillStyle = "#000000";
		context.fillRect(0,0,512,512);
		var randomcolor = Std.random(16777216);
		var tmp = StringTools.hex(randomcolor,6);
		context.fillStyle = "#" + tmp;
		var _g = 0;
		while(_g < 8) {
			var y = _g++;
			var randn = Std.random(2);
			pattern[y * 4] = randn;
			if(pattern[y * 4] == 1) {
				context.fillRect(0,y * 64,64,64);
				context.fillRect(448,y * 64,64,64);
			}
			var randn1 = Std.random(2);
			pattern[y * 4 + 1] = randn1;
			if(pattern[y * 4 + 1] == 1) {
				context.fillRect(64,y * 64,64,64);
				context.fillRect(384,y * 64,64,64);
			}
			var randn2 = Std.random(2);
			pattern[y * 4 + 2] = randn2;
			if(pattern[y * 4 + 2] == 1) {
				context.fillRect(128,y * 64,64,64);
				context.fillRect(320,y * 64,64,64);
			}
			var randn3 = Std.random(2);
			pattern[y * 4 + 3] = randn3;
			if(pattern[y * 4 + 3] == 1) {
				context.fillRect(192,y * 64,64,64);
				context.fillRect(256,y * 64,64,64);
			}
		}
		context.stroke();
	};
	var generatewithbgbutton = window.document.getElementById("generatewithbgbutton");
	generatewithbgbutton.onclick = function() {
		var bgcolor = Std.random(16777216);
		var tmp = StringTools.hex(bgcolor,6);
		context.fillStyle = "#" + tmp;
		context.fillRect(0,0,512,512);
		var randomcolor = Std.random(16777216);
		var tmp = StringTools.hex(randomcolor,6);
		context.fillStyle = "#" + tmp;
		var _g = 0;
		while(_g < 8) {
			var y = _g++;
			var randn = Std.random(2);
			pattern[y * 4] = randn;
			if(pattern[y * 4] == 1) {
				context.fillRect(0,y * 64,64,64);
				context.fillRect(448,y * 64,64,64);
			}
			var randn1 = Std.random(2);
			pattern[y * 4 + 1] = randn1;
			if(pattern[y * 4 + 1] == 1) {
				context.fillRect(64,y * 64,64,64);
				context.fillRect(384,y * 64,64,64);
			}
			var randn2 = Std.random(2);
			pattern[y * 4 + 2] = randn2;
			if(pattern[y * 4 + 2] == 1) {
				context.fillRect(128,y * 64,64,64);
				context.fillRect(320,y * 64,64,64);
			}
			var randn3 = Std.random(2);
			pattern[y * 4 + 3] = randn3;
			if(pattern[y * 4 + 3] == 1) {
				context.fillRect(192,y * 64,64,64);
				context.fillRect(256,y * 64,64,64);
			}
		}
		context.stroke();
	};
	var changebgbutton = window.document.getElementById("changebgbutton");
	changebgbutton.onclick = function() {
		var randomcolor = Std.random(16777216);
		var tmp = StringTools.hex(randomcolor,6);
		context.fillStyle = "#" + tmp;
		var _g = 0;
		while(_g < 8) {
			var y = _g++;
			if(pattern[y * 4] == 0) {
				context.fillRect(0,y * 64,64,64);
				context.fillRect(448,y * 64,64,64);
			}
			if(pattern[y * 4 + 1] == 0) {
				context.fillRect(64,y * 64,64,64);
				context.fillRect(384,y * 64,64,64);
			}
			if(pattern[y * 4 + 2] == 0) {
				context.fillRect(128,y * 64,64,64);
				context.fillRect(320,y * 64,64,64);
			}
			if(pattern[y * 4 + 3] == 0) {
				context.fillRect(192,y * 64,64,64);
				context.fillRect(256,y * 64,64,64);
			}
		}
		context.stroke();
	};
	var changefgbutton = window.document.getElementById("changefgbutton");
	changefgbutton.onclick = function() {
		var randomcolor = Std.random(16777216);
		var tmp = StringTools.hex(randomcolor,6);
		context.fillStyle = "#" + tmp;
		var _g = 0;
		while(_g < 8) {
			var y = _g++;
			if(pattern[y * 4] == 1) {
				context.fillRect(0,y * 64,64,64);
				context.fillRect(448,y * 64,64,64);
			}
			if(pattern[y * 4 + 1] == 1) {
				context.fillRect(64,y * 64,64,64);
				context.fillRect(384,y * 64,64,64);
			}
			if(pattern[y * 4 + 2] == 1) {
				context.fillRect(128,y * 64,64,64);
				context.fillRect(320,y * 64,64,64);
			}
			if(pattern[y * 4 + 3] == 1) {
				context.fillRect(192,y * 64,64,64);
				context.fillRect(256,y * 64,64,64);
			}
		}
		context.stroke();
	};
	var downloadbutton = window.document.getElementById("downloadbutton");
	downloadbutton.onclick = function() {
		var data = drawingcanvas.toDataURL("image/png");
		window.location.href = StringTools.replace(data,"image/png","image/octet-stream");
	};
};
var Std = function() { };
Std.random = function(x) {
	if(x <= 0) {
		return 0;
	} else {
		return Math.floor(Math.random() * x);
	}
};
var StringTools = function() { };
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
StringTools.hex = function(n,digits) {
	var s = "";
	var hexChars = "0123456789ABCDEF";
	while(true) {
		s = hexChars.charAt(n & 15) + s;
		n >>>= 4;
		if(!(n > 0)) {
			break;
		}
	}
	if(digits != null) {
		while(s.length < digits) s = "0" + s;
	}
	return s;
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
